pipeline {
    agent any
    tools {
        jdk 'jdk1.8'
        maven 'localmaven'
    }
    stages{
          stage('maven-build') {
                 dir('mmproot') {
                       sh 'mvn clean install'
                 }
          }
     }
}
