def temp_var =''
pipeline {
    agent any
    tools {
        jdk 'jdk1.8'
        maven 'localmaven'
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage('maven-build') {
            steps {
                dir('mmproot') {
                    sh 'mvn clean install'
                    echo "${params.CHOICE}"

                    echo "Hello ${params.PERSON}"

                    echo "Biography: ${params.BIOGRAPHY}"

                    echo "Toggle: ${params.TOGGLE}"

                    echo "Choice: ${params.CHOICE}"

                    echo "Password: ${params.PASSWORD}"
                }
            }
        }

        stage('call_liquibase-project') {
            steps {
                script {
                    def readPOm = load '/tmp/readpomScript.groovy'
                    temp_var = readPOm.parsePom('some garbage')
                }
                echo "${temp_var}"
                build job: 'liquibase_pipeline/master', parameters: [string(name: 'BUILD_VERSION', value: "${temp_var}")], wait: true
            }
        }
    }
}
